### ISSUE TITLE
One class per file

### ISSUE THREAD

**Issue by vmartirosyan** [kamosevoyan/TuringLanguage_compiler#1]
Separate the code into several files, so that each class is contained in a file with the same name (both header and cpp files).

https://github.com/kamosevoyan/TuringLanguage_compiler/blob/104342cdf1dce0f9eb0c4e140a4384014bf4fbdf/src/TuringLanguage.cpp#L55

**Comment by kamosevoyan** [comment]
I have corrected the issue you've mentioned.
