### ISSUE TITLE
Better debug implementation

### ISSUE THREAD

**Issue by vmartirosyan** [kamosevoyan/TuringLanguage_compiler#2]
Implement several macros - Debug(), Info(), ... and just call them from the code without any condition checks. The check might be done in the macros themselves.

https://github.com/kamosevoyan/TuringLanguage_compiler/blob/104342cdf1dce0f9eb0c4e140a4384014bf4fbdf/src/TuringLanguage.cpp#L151

**Comment by kamosevoyan** [comment]
I decided not to have debug in this project.
